version: '3'

services:
  photos:
    build: .
    ports: 
      - '3001:3001'
    depends_on:
      - 'database'  
    command: sh -c 'npm run seed-db; npm start'

  database:
    image: mongo:latest
